export const ADD_FILTER = 'ADD_FILTER'
export const DELETE_FILTER = 'DELETE_FILTER'
export const SET_SEARCH = 'SET_SEARCH'
export const GET_RESULTS = 'GET_RESULTS'
export const DO_SEARCH = 'DO_SEARCH'
export const LOAD_MORE = 'LOAD_MORE'